# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "hashicorp/bionic64"

  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "./config", "/config"
  config.vm.synced_folder "./scripts", "/scripts"
  config.vm.synced_folder "./plugins", "/plugins"
  config.vm.synced_folder "./benchmark", "/benchmark"
  config.vm.synced_folder "./results", "/results", :create => true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = 4096
    vb.cpus = 4
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     apt-get -q update

     #installing docker as per https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
     echo "Installing docker..."
     apt-get -q install -y apt-transport-https ca-certificates curl software-properties-common
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
     apt-get -q update
     apt-cache policy docker-ce
     apt-get -q install -y docker-ce
     systemctl status docker

     # setting up vagrant user to run without sudo
     sudo usermod -aG docker ${USER}
     sudo su - ${USER}
     id -nG
     docker version
     clean-docker

     # installing docker-compose
     echo "Installing docker-compose..."
     curl -sL https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
     chmod +x /usr/local/bin/docker-compose
     docker-compose --version

    sudo apt-get install -y python3-pip
    pip3 install openpyxl
    python3 /scripts/scan.py
  SHELL
end